### ISSUE TITLE
Option to disable the firefox search engine.

### ISSUE THREAD

**Issue by isweethero** [YellowFish085/al-search#14]
Hi, thank you for this awesome extension!
In the firefox version, after deleting the search engine and re-opening firefox, the search engine comes back. There is a option to disable this behavior? Thank You!

![image](https://user-images.githubusercontent.com/38861963/118648241-96fd9a00-b7b8-11eb-9a8c-4ef54ccd05fe.png)

**Comment by YellowFish085** [comment]
Heya,

First I'm happy to hear you're enjoying the extension, it's nice to have good feedbacks ☺️

For your question, I don't really know if this is possible. The docs provided by Mozilla and Google about search engines in add-ons are pretty thin so what I'm saying is more like an educated guess rather than official facts, but from what I understand a search engine added by an add-on can't be removed unless you remove the add-on itself. It also appears that for some unknown reasons you can't even disable it but I don't know if this is a bug on my browser or something global.

To be honest the search engine part of AL Search is more like an extra bonus thing that I added simply because it was quick and simple to do and didn't need any kind of real maintenance. I almost removed it completely before releasing the add-on because it felt weird to only have it on Firefox and not Chrome, but in the end it didn't cost anything to keep it so here we are.

Looking at the doc there is no way to make this feature optional so I can't go that way, so the only option I have is to remove it completely... but I don't really want to do that because some people might use it.

Is there any issue with it on your side regarding the search engine that makes you want to remove it (idk, maybe the keyword that triggers the search engine is always triggering it so it's a pain for you to have it) or is it just because you simply want to remove it?

**Comment by isweethero** [comment]
Removing search engines removes the last menu. I often missclick up, and that brings the settings.

![image](https://user-images.githubusercontent.com/38861963/118662140-28273d80-b7c6-11eb-998d-72176dc27b65.png)

When there are no search engines:
![image](https://user-images.githubusercontent.com/38861963/118662283-43924880-b7c6-11eb-8b0d-fa8fd2c1d15c.png)

**Comment by YellowFish085** [comment]
I see, unfortunately I don't think there is something that could be done on my end except to completely remove the search engine, which I'll not do for reasons I already explained.

It seems that a search engine added by an add-on can't be removed nor disabled, that's how Firefox works (at least based on my research and observations) and I don't have control over that behaviour. I tried to look if there was something that could be done on the browser itself to help you with your issue but I didn't find anything, so yeah sorry :/

I'm gonna close this issue since it's not something that can be "fixed" on AL Search, hope this wont bother you too much.
